import Generator from "./Generator";
import Parser from "./Parser";
import ReflectionFactory from "./ReflectionFactory";
import Babel from "./Transpiler/Babel/Babel";
import Deployer from "./Deployer/Deployer";
import Nodemon from "./Executor/Nodemon/Nodemon";
import PackageJson from './PackageJson';
import FilePath from "./FilePath";

import program from 'caporal';
import clear from 'clear';
import chalk from 'chalk';
import figlet from 'figlet';
import inquirer from 'inquirer';



let instance = null;
export default class App {
    constructor () {
        // singleton
        if (instance) {
            return instance;
        }
        instance = this;

        // init singleton object
        App.initSingleton();
        // add class meta to reflection factory.
        App.initClass();
        // init all objects needed.
        this.parser_ = new Parser();
        const parseRes_ = this.parser_.grammarList();
        this.generator_ = new Generator(parseRes_);

        const filePath = new FilePath();
        this.projectPackageJson_ = new PackageJson(filePath.packageJsonPath());
        this.pwdPackageJson_ = new PackageJson(filePath.workingPackageJsonPath());
    }

    static initSingleton() {
        //new ConfigFile();
    }

    static initClass () {
        ReflectionFactory.addClass(Babel);
        ReflectionFactory.addClass(Nodemon);
        ReflectionFactory.addClass(Deployer);
    }

    run () {
        clear();
        // hello message
        console.log(
            chalk.yellow(
                figlet.textSync('htwb', { horizontalLayout: 'full' })
            )
        );
        const self = this;
        const content = self.projectPackageJson_.content();
        const version = content['version'];
        program
            .version(version)
            .description('Generate npm scripts for full stack web development.');

        program
            .command('project', 'Create an empty project.')
            .alias('p')
            .action(() => {
                self.createProject();
            });
        program
            .command('backend', 'Generate back end building npm scripts or command line building npm scripts.')
            .alias('b')
            .action((args, options, logger) => {
                self.generateBackend(args, options, logger);
            });
        program
            .command('remove', 'Remove npm scripts generated by htwb in package.json file.')
            .alias('r')
            .action((args, options, logger) => {
                self.removeScripts(args, options, logger);
            });

        program.parse(process.argv);
    }

    createProject (args, options, logger) {
        logger.info('Create empty project!');
        logger.info(`${__dirname}`);
        logger.info(`${process.env.PWD}`);
    }

    generateBackend (args, options, logger) {
        logger.info('Generate back end npm scripts...');
        /*logger.debug('args: ', args);
        logger.debug('options: ', options);*/
        if (this.pwdPackageJson_.isScriptExist()) {
            throw new Error('The package.json file has contained scripts generated by htwb, ' +
                'if you want to regenerate all scripts, please run \'htwb remove\' firstly.');
        }
        const content = this.pwdPackageJson_.content();
        let scriptSection = content['scripts'] || {};

        logger.debug('App.generateBackend() scriptSection: ', scriptSection);

        this.generator_.generate(scriptSection);
        logger.debug('App.generateBackend() scriptSection after generate: ', scriptSection);

        this.pwdPackageJson_.writeScriptsToPackageJsonFile(scriptSection);
    }

    async removeScripts(args, options, logger) {
        let questions = [{
            name: 'sureDelete',
            message: 'Are you sure to delete all generated scripts?',
            type: 'confirm',
            default: false,
            validate: (str) => {
                return (str === 'Y' || str === 'n');
            }
        }];

        let answers = await inquirer.prompt(questions);
        logger.debug(`App.removeScripts() answers: ${JSON.stringify(answers)}`);
        if (answers['sureDelete']) {
            this.pwdPackageJson_.removeGeneratedScripts(logger);
        }
    }
}
